### ISSUE TITLE
Build with --watch flag

### ISSUE THREAD

**Issue by enejm** [simondotm/nxfirebase#11]
Hello. Great plugin. 
Is there a way to run the builder in watch mode for hot reloading purpose?

I have tried 
`nx build myapp --watch=true`

It starts compilation in watch mode but it exits after first execution.

**Comment by simondotm** [comment]
Interesting question. Can I ask how you would be using `--watch` with functions? Is it for just checking for compile errors as you work, or for some other interesting reason?

**Comment by simondotm** [comment]
Looks like this was a bug in Nx thats fixed in 12.3.4 - Nx issue 5208
Plugin may need to rearrange the order it does its work however to:
1. Build dependent libraries
2. Copy libraries to dist
3. Update package.json
4. TSC compile the functions library (has to be the last step in case of watch mode)

`--watch` should work in this case. However changes to dependent libraries wont be detected for rebuilding the functions app output.

**Comment by simondotm** [comment]
I dont think it's going to be trivial to support --watch because we do post processing on the build. I cant do the tsc step last, because it deletes the output folder before compilation (which nukes the package.json and local library deps we've created).

Hmmm....

**Comment by enejm** [comment]
Regarding the use case:

In regular firebase functions repo I mostly use
`npm run build -- --watch | firebase emulators:start` 
This way I can test functions in functions shell or in frontend app without need to manually rebuild it on every change.

So in regards to issue #9  - I intended to set up `nx serve` with build command using --watch flag

Ideal dev experience for fullstack development would be: 
To serve both functions and frontend app, and any change in apps and especially in common libs would be applied without need to manually rebuild and rerun emulators again.

**Comment by enejm** [comment]
Hmm, yes, I understand. If it is not trivial issue, than I will stick to "manual". :) Thank you for your time.

**Comment by simondotm** [comment]
Thanks for the extra info. I've got an idea there might be a way to do this, and its a useful thing for the plugin to do, so I'll look into it.

**Comment by simondotm** [comment]
Ok I've figured this out. --watch will be supported in the next release.

**Comment by simondotm** [comment]
[v0.2.3 now released against Nx version 12.3.4](https://www.npmjs.com/package/@simondotm/nxfirebase)

`--watch` is now supported in v0.2.3 - requires minimum Nx version 12.3.4

**Comment by simondotm** [comment]
@enejm - Please note project has now been renamed to `@simondotm/nx-firebase`, see [here](https://www.npmjs.com/package/@simondotm/nx-firebase) for the new 0.3.0 release.
