### ISSUE TITLE
Firebase Executor for emulator suite

### ISSUE THREAD

**Issue by KingDarBoja** [simondotm/nxfirebase#9]
Hi, awesome plugin, been using it a bit for experimenting with sharing code between firebase functions and angular apps.

Wanted to know if the firebase executor can be documented or configured to support emulators parameters.

Right now I am doing something like below at angular.json for serve the CF locally with emulators.
```json
{

        "serve": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              {
                "command": "nx run appName:build"
              },
              {
                "command": "firebase use projectIdOrAlias"
              },
              {
                "command": "firebase emulators:start --config firebase.appName.json"
              }
            ],
            "parallel": false
          }
        }
}
```

Cheers!

**Comment by KingDarBoja** [comment]
I forgot to mention that trying to run the emulators will yield an error and abort such operation:

![image](https://user-images.githubusercontent.com/30560560/118826822-6c2b4880-b881-11eb-9110-5febe40e0d79.png)

Not sure if related to the library setup itself as it is the first time I encountered the error.

**Comment by simondotm** [comment]
Ok thanks for the extra info, I've not used the emulators so far, so this is a good opportunity to get more familiar with them

**Comment by KingDarBoja** [comment]
Btw, looks like the issue is caused by the following:

>  The Cloud Functions emulator requires the module "firebase-admin" to be installed as a dependency. To fix this, run "npm install --save firebase-admin" in your functions directory.
i  functions: Your functions could not be parsed due to an issue with your node_modules (see above)

So I added both `firebase-admin` and `firebase-functions` to the package.json inside the firebase app:

```
  "dependencies": {
    "firebase-admin": "^9.8.0",
    "firebase-functions": "^3.14.1"
  },
```

![image](https://user-images.githubusercontent.com/30560560/118895682-3cedf900-b8cc-11eb-92df-12f0ccf766b9.png)

**Comment by simondotm** [comment]
Sweet! You got it working! Thanks for sharing that. Interesting about that firebase-admin dep, because Max mentioned a similar (unrelated issue) with that too -https://github.com/simondotm/nxfirebase/issues/7#issue-891665170
Ok I think I'll change the package template to somehow have admin and functions deps in as a default. I didn't want to put them in the template since they'll not get overwritten if versions in the root package get updated, I'll figure it out though.
Thanks again.

**Comment by simondotm** [comment]
Or I could `import firebase-admin` in the default `index.ts`... hmm

**Comment by KingDarBoja** [comment]
> Or I could `import firebase-admin` in the default `index.ts`... hmm
> (all of my functions do import firebase-admin at some point, so I didn't see this occur until these examples came up)

Ummmm... I accidentally removed it while testing the grouped functions feature, I can give it a try like that.

Also noticed that I must keep an empty `firebase.json` file at root and move the hosting config to the project specific json file to properly initialize the hosting emulator. I will share my example nx workspace in a few minutes.

**Comment by simondotm** [comment]
> Also noticed that I must keep an empty firebase.json file at root and move the hosting config to the project specific json file to properly initialize the hosting emulator. I will share my example nx workspace in a few minutes.

There's a note in the readme about this - if you are only using one firebase application in your nx workspace, you can just delete the empty `firebase.json` and rename your `firebase.appname.json` to just `firebase.json` (and this way you dont need the `--config` part in firebase CLI commands)

**Comment by simondotm** [comment]
This is all great feedback, thanks. I'll incorporate these improvements into the next release.

**Comment by simondotm** [comment]
Also @KingDarBoja - thanks for the `ignoreUndefinedProperties: true` tip - I wasn't aware of this little gem, drives me nuts when there's exceptions due to an undefined field creeping in somewhere!

**Comment by simondotm** [comment]
Hey @KingDarBoja - why do you have the `firebase use projectIdOrAlias`  command in your serve target?
I'm trying to understand if that is required for the emulators to work? (since firebase use selects a remote deployment instance, not a local instance)

**Comment by simondotm** [comment]
[v0.2.3 now released against Nx version 12.3.4](https://www.npmjs.com/package/@simondotm/nxfirebase)

Ok I've added `serve` and `deploy` targets to the application generator which support the use cases above. I dont have a migration script for the plugin so existing NxFirebase apps will need to manually change their targets as follows:

```
        "serve": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              {
                "command": "nx run appname:build --watch"
              },
              {
                "command": "firebase emulators:start --config firebase.appname.json"
              }
            ],
            "parallel": true
          }
        },
        "deploy": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "firebase deploy --config firebase.appname.json"
          }
        },
```

**Comment by simondotm** [comment]
@KingDarBoja - Please note project has now been renamed to `@simondotm/nx-firebase`, see [here](https://www.npmjs.com/package/@simondotm/nx-firebase) for the new 0.3.0 release.

**Comment by KingDarBoja** [comment]
> Hey @KingDarBoja - can I ask why you have the `firebase use projectIdOrAlias` command in your serve target?
> I'm trying to understand if that is required for the emulators to work? (since the `firebase use` command selects a remote deployment instance, not a local instance)
> 
> Would it work with just:
> 
> ```
>             "commands": [
>               {
>                 "command": "nx run appName:build"
>               },
>               {
>                 "command": "firebase emulators:start --config firebase.appName.json"
>               }
>             ],
> ```

Because the cli will start blaming and stop the emulators to run with the following error:
```
emulators: The Emulator UI requires a project ID to start. Configure your default project with 'firebase use' or pass the --project flag.
```

**Comment by KingDarBoja** [comment]
@simondotm tried the latest version (0.3.1) and the emulators are working perfectly. No clue why the previous error was showing up regarding the project id but seems it is already picking the default one :)

![image](https://user-images.githubusercontent.com/30560560/119420785-eebd6900-bcc2-11eb-8985-cc99115e7a14.png)
